num1 = int(input("Write first number: "))
num2 = int(input("Write second number: "))
plus = num1 + num2
minus = num1 - num2
eval = num1 * num2
diver = num1 / num2
print ("{0} + {1} = {2}". format(num1,num2,plus))
print ("{0} - {1} = {2}". format(num1,num2,minus))
print ("{0} * {1} = {2}". format(num1,num2,eval))
print ("{0} / {1} = {2}". format(num1,num2,diver))